export const COLUMNS = [
    {
        Header:"FirstName",
        accessor:'first_name'
    },
    {
        Header:"LastName",
        accessor:'last_name'
    },
    {
        Header:"DOB",
        accessor:'date_of_birth'
    },
    {
        Header:"Email",
        accessor:'email'
    },
    {
        Header:"Gender",
        accessor:'gender'
    },
    {
        Header:"Country",
        accessor:'country'
    },
]